import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  content: {
    paddingTop: 58,
    paddingHorizontal: 20,
    paddingBottom: 96,
  },
  title: {
    fontSize: 26,
    color: "#0f172a",
    fontWeight: "700",
    marginBottom: 14,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 14,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "700",
    marginBottom: 4,
  },
  description: {
    fontSize: 12,
    lineHeight: 18,
    color: "#64748b",
    marginBottom: 12,
  },
  fakeInputRow: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  fakeLabel: {
    color: "#64748b",
    fontSize: 12,
  },
  fakeValue: {
    color: "#0f172a",
    fontSize: 12,
    fontWeight: "600",
    flex: 1,
    textAlign: "right",
  },
  value: {
    color: "#0f766e",
    fontSize: 13,
    fontWeight: "700",
  },
  primaryButton: {
    marginTop: 4,
    borderRadius: 12,
    backgroundColor: "#0f766e",
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 13,
  },
  paymentMethods: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    marginBottom: 10,
  },
  methodChip: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  methodChipActive: {
    backgroundColor: "#ccfbf1",
    borderColor: "#5eead4",
  },
  methodText: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "600",
  },
  methodTextActive: {
    color: "#0f766e",
    fontSize: 12,
    fontWeight: "700",
  },
  receiptBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ecfeff",
    borderWidth: 1,
    borderColor: "#99f6e4",
    borderRadius: 12,
    padding: 10,
    gap: 8,
  },
  receiptText: {
    color: "#0f172a",
    fontSize: 12,
    flex: 1,
  },
  sectionTitle: {
    marginTop: 6,
    marginBottom: 8,
    fontSize: 15,
    color: "#0f172a",
    fontWeight: "700",
  },
  historyCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
    marginBottom: 8,
  },
  historyTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  historyPoint: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "700",
  },
  historyStatus: {
    color: "#0369a1",
    backgroundColor: "#e0f2fe",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "700",
  },
  historyMeta: {
    marginTop: 4,
    fontSize: 12,
    color: "#64748b",
  },
  historyValue: {
    marginTop: 8,
    color: "#0f766e",
    fontSize: 14,
    fontWeight: "700",
  },
});
